### ISSUE TITLE
Realm Issue - setAdapter();

### ISSUE THREAD

**Issue by haninkyu** [haninkyu/GDG_Heyden#6]
01-29 05:55:01.142 2975-2975/nive.sampleview E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: nive.sampleview, PID: 2975
                                                               java.lang.NoSuchMethodError: No virtual method findAllSorted(Ljava/lang/String;Z)Lio/realm/RealmResults; in class Lio/realm/RealmQuery; or its super classes (declaration of 'io.realm.RealmQuery' appears in /data/app/nive.sampleview-1/base.apk)
                                                                   at co.moonmonkeylabs.realmsearchview.RealmSearchAdapter.filter(RealmSearchAdapter.java:99)
                                                                   at co.moonmonkeylabs.realmsearchview.RealmSearchView.setAdapter(RealmSearchView.java:86)
                                                                   at nive.sampleview.view.fragment.LocalFragment.onViewCreated(LocalFragment.java:61)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                   at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                   at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
                                                                   at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
                                                                   at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
                                                                   at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:1778)
                                                                   at android.support.design.widget.TabLayout.selectTab(TabLayout.java:871)
                                                                   at android.support.design.widget.TabLayout.selectTab(TabLayout.java:841)
                                                                   at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1115)
                                                                   at android.support.design.widget.TabLayout$1.onClick(TabLayout.java:665)
                                                                   at android.view.View.performClick(View.java:4756)
                                                                   at android.view.View$PerformClick.run(View.java:19749)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by haninkyu** [comment]
0.9.1 버전과 0.9.4 버전의 혼용으로 인한 에러.
버전을 통일하고 해당 예제소스대로 메소드를 정리하자 작동됨
